### ISSUE TITLE
Disallow css selector tied to page layout doesn't work with template strings

### ISSUE THREAD

**Issue by VladimirCW** [kwoding/eslint-plugin-ui-testing#1]
//this doesn't work -  linter doesn't define the  error
private get _test(): WebdriverIO.Element {
    return $(\`.abc #def > ["data-test"="test"]\`);
}

//this works well - linter defines the error
private get _test2(): WebdriverIO.Element {
    return $('.abc #def > ["data-test"="test"]');
}

**Comment by kwoding** [comment]
Thanks for raising this. Added support for template string in version 0.3.0
