### ISSUE TITLE
Disallow css selector tied to page layout doesn't work with concatenated strings

### ISSUE THREAD

**Issue by VladimirCW** [kwoding/eslint-plugin-ui-testing#2]
// this works well - linter defines the error
private get _test2(): WebdriverIO.Element {
    return $('.abc #def > ["data-test"="test"]');
}

// this doesn't work - linter doesn't define the error
private get _test3(): WebdriverIO.Element {
    return $(selectors.x + ' ' + selectors.z + ' > ' + selectors.y);
}

// this doesn't work - linter doesn't define the error
private get _test3(): WebdriverIO.Element {
        return $('.abc' + ' ' + '#def' + ' > ' + '["data-test"="test"]');
    }

**Comment by kwoding** [comment]
In version 0.3.0 (see #1) the support for template strings is added. For concatenated strings the convention is actually this rule: https://eslint.org/docs/rules/no-useless-concat (not part of this plugin) and to use template strings if variables need to be included.
