### ISSUE TITLE
Missing assertion in test  even though I have expect condition

### ISSUE THREAD

**Issue by umagsfx** [kwoding/eslint-plugin-ui-testing#22]
import { expect, test } from '@playwright/test';
import { BasePage } from '../pages/BasePage';
import { LoginPage } from '../pages/LoginPage';
import { LogoutPage } from '../pages/LogoutPage';
import { EditPage } from '../pages/editPage';

test.use({ launchOptions: { slowMo: 1000 } });

test.describe('Test Suite', () => {
  test('login page test', async ({ page }) => {
    const basePage = new BasePage(page);
    const loginPage = new LoginPage(page);
    const logoutPage = new LogoutPage(page);
    const editPage = new EditPage(page);

    await basePage.navigate();
    await loginPage.login();
    await loginPage.selectWorkSpace();
    const returnTest = await loginPage.verifyMessage();
    expect(returnTest).toBeTruthy();
    await editPage.clickEditInputButton();
    await editPage.clickEditInputButton();
    await editPage.testButtons();
    await logoutPage.logout();
    expect(true).toBeTruthy();
  });
});

**Comment by kwoding** [comment]
Thanks for raising this issue. Fixed in version `2.0.1`

**Comment by umagsfx** [comment]
Thank you.
