### ISSUE TITLE
Disallow tests without assertions doesn't define assertion if it is imported from another function

### ISSUE THREAD

**Issue by VladimirCW** [kwoding/eslint-plugin-ui-testing#3]
//here is the test
it(\`Some test\`, () => {
        const actualResult = homePage.someField;
        //assertion is imported from another class
        Tests.someCheck(actualResult);
});

//Example of imported tests
class Tests {
    static someCheck = (argument) => {
        expect('1').to.be.equal(argument);
    }
}

**Comment by kwoding** [comment]
Yep, with custom assert functions like this, the rule can be configured as follows:

```
{
    "ui-testing/missing-assertion-in-test": [
        "error",
        {
            "assertCommands": ["someCheck"]
        }
    ]
}
```
