### ISSUE TITLE
Xpath selectors that starts with '(' are defined as tied to layout

### ISSUE THREAD

**Issue by VladimirCW** [kwoding/eslint-plugin-ui-testing#5]
(//*[contains(@class, 'someClass')])[2]

**Comment by kwoding** [comment]
Extended the unit tests with this use case. However the rule seems to be working correctly. It seems to be a quote issue:

working: `$('//*[contains(@Class, "someClass")])[2]')`
not working: `$('//*[contains(@Class, \'someClass\')])[2]')` (cannot parse, note the multiple usage of single quotes)

**Comment by VladimirCW** [comment]
Their is no open paranthesis in selector added test '(', before '//'

пт, 17 июл. 2020 г., 21:54 Kwo Ding <notifications@github.com>:

**Comment by kwoding** [comment]
Sorry, I misread the xpath string. Thanks for finding this. Fixed in version 0.4.0
