### ISSUE TITLE
Specify rule name for "Disallow link text selector" in format "ui-testing/no-link-text-selector"

### ISSUE THREAD

**Issue by VladimirCW** [kwoding/eslint-plugin-ui-testing#7]
File with instruction https://github.com/kwoding/eslint-plugin-ui-testing/blob/master/docs/rules/no-link-text-selector.md
doesn't have a proper rule name.
I found that it should be "ui-testing/no-link-text-selector": "warn".

Other rules the same problem - it can be difficult to guess that name of the rule is in the file name

**Comment by kwoding** [comment]
Good point, I updated the readme to include the rule names.
