### ISSUE TITLE
Disallow tests without assertions doesn't define assertion if it is imported from another class method

### ISSUE THREAD

**Issue by VladimirCW** [kwoding/eslint-plugin-ui-testing#8]
//here is the test
const tests = new Tests();
it(`Some test`, () => {
    const actualResult = homePage.someField;
    //assertion is imported from another class
    tests.someCheck(actualResult);
});

//Example of imported tests
class Tests {
    someCheck = (argument) => {
    expect('1').to.be.equal(argument);
}
}

I tried to add 
`"ui-testing/missing-assertion-in-test": [
      "error",
      {
        "assertCommands": [
          "expect",
          "tests.someCheck"
        ]
      }
    ]`
 to `.eslintrc.json` file, but this doesn't work if the assertion is imported as a class method.
Instead, assertion imported as a single function works properly
`"ui-testing/missing-assertion-in-test": [
      "error",
      {
        "assertCommands": [
          "expect",
          "someMethod"
        ]
      }
    ]`

**Comment by kwoding** [comment]
Is `"ui-testing/missing-assertion-in-test": [ "error", { "assertCommands": [ "expect", "someCheck" ] } ]` workable for your case?
