### ISSUE TITLE
Issue with option name in the 'no-wait-in-tests.md' file

### ISSUE THREAD

**Issue by mshykov** [kwoding/eslint-plugin-ui-testing#9]
It seems there is an issue with an option name in MD-file for the [`no-wait-in-tests`](https://github.com/kwoding/eslint-plugin-ui-testing/blob/master/docs/rules/no-wait-in-tests.md#options) rule: 
```js
{
    "ui-testing/no-hard-wait": ["error", "webdriverio"]
}
```

But should be:
```js
{
    "ui-testing/no-wait-in-test": ["error", "webdriverio"]
}
```
Does it?

**Comment by kwoding** [comment]
Thanks for raising this, fixed the docs.
